server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: calculo-service
          uri: lb://calculo-service
          predicates:
            - Path=/calculo/**

        - id: evaluacion-service
          uri: lb://evaluacion-service
          predicates:
            - Path=/evaluacion/**

        - id: registro-service
          uri: lb://registro-service
          predicates:
            - Path=/registro/**

        - id: seguimiento-service
          uri: lb://seguimiento-service
          predicates:
            - Path=/seguimiento/**

        - id: simulacion-service
          uri: lb://simulacion-service
          predicates:
            - Path=/simulacion/**

        - id: solicitud-service
          uri: lb://solicitud-service
          predicates:
            - Path=/solicitud/**