server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: Calculo
          uri: lb://Calculo
          predicates:
            - Path=/calculo/**
        - id: Evaluacion
          uri: lb://Evaluacion
          predicates:
            - Path=/evaluacion/**
        - id: Registro
          uri: lb://Registro
          predicates:
            - Path=/api/v1/client/**
        - id: Seguimiento
          uri: lb://Seguimiento
          predicates:
            - Path=/seguimiento/**
        - id: Simulacion
          uri: lb://Simulacion
          predicates:
            - Path=/simulacion/**
        - id: Solicitud
          uri: lb://Solicitud
          predicates:
            - Path=/solicitud/**