server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  cloud:
    config:
      enabled: true
      uri: http://config-service-service:8081
  datasource:
    url: jdbc:postgresql://registro-db-service:5432/registro-db
    username: postgres
    password: niko2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/